// Generated by https://quicktype.io

// Datos para envío y validación del Login
export interface DatosLogin {
    PasswordUsuario: string;
    NombreUsuario: string;
    idEmpresa: number;
    dispositivo: string;
    tipo?: string
}
